### ISSUE TITLE
[ALL] 운영정책 정하기 (참신함!)

### ISSUE THREAD

**Issue by raheego** [T2-Papillon/Main#15]
![image](https://github.com/T2-Papillon/Main/assets/54056684/3ed802b5-0125-4111-8d4a-47520657ec03)

우리 기능에 대한 정책을 세워야 합니다. 
<br>

## 논의사항
1. 통계 기능을 어떻게 설정할지?
2. 투표 기능을 어떻게 설정할지?
3. 응원 기능을 어떻게 설정할지?

**Comment by Afresh2** [comment]
## 투표 기능 넣기

**Comment by Afresh2** [comment]
> ## 투표 기능 넣기
> * 여러명의 사용자가 업무에 대한 일정을 정할 때, 어떤 일정을 하고자 할지 투표하는 기능
> * 불가능한 일정에 대해서 투표한다?

안녕

**Comment by choi3179** [comment]
> ## 투표 기능 넣기
> * 여러명의 사용자가 업무에 대한 일정을 정할 때, 어떤 일정을 하고자 할지 투표하는 기능
> * 불가능한 일정에 대해서 투표한다?

- 이렇게 할까요?

**Comment by choi3179** [comment]
## 통계 기능 컨텐츠
### 횟수 통계
- 월별 일정 개수 통계를 차트로 표시
- 1주 or 1달 단위로 그 기간동안 어느 시간대에 일을 많이 했는지 차트로 표시
### 목표 달성률

### 협업 랭킹

**Comment by raheego** [comment]
## 일정 응원하기
