### ISSUE TITLE
1차 멘토링 회의록 정리

### ISSUE THREAD

**Issue by raheego** [T2-Papillon/Main#16]
- 멘토링 전 사전질문리스트 참고 
- https://github.com/T2-Papillon/Main/issues/9

**Comment by raheego** [comment]
```
[개인]
Q. 한화시스템에서 메인으로 잡고 계시는 분야가 어떤 건가요.
- 입출금 안내 장부 담당, 부서 내 인원 총 8명 

Q. 면접 들어가시나요. 포트폴리오를 보실 때 주로 확인하는 부분이 있으신가요.
- 경력직 면접만 참여 ,경력직 면접 다수 
- 지금 업무에서 쓰이는 기술들을 사용해봤는지에 대해 봄
- 면접자가 무엇을 했는지 보다  '어떻게' 했는가, 인성 중점
- 협업과 커뮤니케이션
- 본인이 했던 역할이 실무에서 사용하는지 
- 포폴 내 주장이 명확하게도 있지만 함께 일을 했을 때 부담이 없겠다

Q. 멘토링에서 어떤 부분을 위주로 멘토링을 해주실 예정인지 궁금합니다. 
- 결과물보다는 과정들에 대해서 스텝들을 가이딩 안내 방향성

[프로젝트]
Q. 현업에서 일정 관리 때 필요한 기능인데 저희가 생각하지 못 한 부분이 있을까요.
- 초반에 설게를 탄탄해하면서 갈지 or 의견을 나누면서 빌드하고 애자일하면서 갈건지
- 먼저 방향성 고려

Q.  보안을 위해 Spring Jwt를 사용한다고 배웠는데 실제 현업에서도 사용하시나요. 이번 프로젝트에 같이 추가하는게 좋을까요.
- 난감하다 솔직히 큰 의미는 없다고 봄 
- 여력이 되는지 여부에 따라 다르다고 판단

Q. 일정관리에 대한 차별성이 있어야 한다면 어떤게 있을까요. 우리가 생각한 차별성에 대한 피드백 사항
- 차별성이라는 단어가 위험하다 생각.
- 획기적인건 이미 시장에 많다 막상 회사에서 쓰냐고 하면 ㄴㄴ = 익숙한걸 실무에서 쓰기 때문
- 대부분은 일정관리가 엑셀에 기입하는 정도 

Q. 저희가 진행하는 이와 같은 프로젝트에서, 어떤 태도 또는 어떤 프로세스 부분을 중요하게 생각하시는지 궁금합니다.
- 시키는것만 ㄴㄴ = 성능 개선 고민흔적 = 적극적 
- 대부분의 사람들이 기한내에 끝내는걸 원하지만 멘토님은 하루이틀이 늦어도 고민의 흔적이 있는 걸 선호
	
```

**Comment by raheego** [comment]
# 멘토링 회의록 - 240307

## 참여자
- 멘토: 남호원
- 팀 구성원: T2-Papillon 팀 멤버들

## 안건
1. 소개
- 참석자 개인 소개
- 참석자 개인의 기술 스택 및 경험 공유.

2. 한화시스템에서의 업무 파악
- 한화시스템에서 대체로 운영 및 유지보수 업무가 주를 이룬다는 점에 대한 공유.

3. 프로젝트 관련 사항
- 프로젝트 진행 방식 및 일정 관리에 대한 계획 설명

4. 요구사항 정의서 및 기타 문서 작성
-요구사항 정의서, 변경 요청서, 컴포넌트 정의서 등의 문서 작성 및 작업 분배 요청

## 상세내용
1. 소개
- 참석자 개인 소개
- 참석자들은 각자의 기술 스택과 경험 공유

2. 한화시스템에서의 업무 파악
- 현재 사용 중인 기술 및 프로그램 소개
- 현재 사용 중인 기술인 자바 형식의 스프링부트, 쿼리원, erwin, 제니퍼 등에 대한 소개가 진행되었다.

3. 프로젝트 관련 사항
- 테스트 및 성능 개선에 중점을 두며, 프로젝트 단계별로 일정을 설정하고 단계마다 완수를 목표로 하고자 했다.
- 현재 설계된 프로젝트 볼륨 줄이기 

4. 요구사항 정의서 및 기타 문서 작성
- 요구사항 정의서, 변경 요청서, 컴포넌트 정의서 등의 문서 작성이 필요하다고 결정되었다.
- 차주 목요일에는 WBS를 중점적으로 논의하고 일정을 잡아나갈 예정이다

### 멘토님 피드백 및 추가 내용
- 프로젝트에서의 데이터 시각화와 대시보드 구현을 고려하여 향후 개발 및 보완할 예정.
- 일정 검색과 사용자 검색에 대한 기능을 필수적으로 고려하여 추가적인 개발을 진행할 예정.
- 팀원들의 개발자로서의 역량 및 성향을 파악하고 효과적인 업무 분배를 위해 차주에는 개발자별 일정 가늠 작업을 진행할 예정.

## 다음 회의
- 차주 목요일(3월 14일)
- 요구사항 정의서 제출

**Comment by Afresh2** [comment]
![LGTM](https://i.lgtm.fun/2q4o.png)
