### ISSUE TITLE
타겟 & 페르소나 선정

### ISSUE THREAD

**Issue by raheego** [T2-Papillon/Main#20]
# [타겟]
- IT 스타트업 개발 회사

# [페르소나]
## 배경
- 이름: 김지훈
- 나이: 30대 중반
- 직업: 스타트업 창업자, CEO
- 경력: IT 및 소프트웨어 개발 분야에서 10년 이상의 경험을 가지고 있음
- 성격: 열정적이고 창의적인 아이디어를 갖고 있으며, 목표를 달성하기 위해 끊임없이 노력하는 타입

## 특징
- 시간 관리의 필요성: 비즈니스 아이디어를 실행하기 위해 다양한 업무를 병행하고 있음. 효율적인 시간 관리가 중요함.
- 다방면 업무: 개발, 마케팅, 금융 등 다양한 부서를 한 사람이 겸하고 있음.
- 이동성: 회의, 고객 미팅, 투자자와의 협의 등 다양한 장소에서 업무를 진행함. 모바일 기기를 자주 사용함.
- 빠른 의사 결정: 스타트업 환경에서의 빠른 의사 결정이 필요함. 정보에 빠르게 접근하고 의사 결정을 내리는 것에 익숙함.

## 일정관리 프로그램을 사용하는 이유
- 효율적인 일정 관리: 다양한 업무를 한꺼번에 관리하기 위해 통합적인 일정 관리가 필요함.
- 다양한 디바이스 지원: 모바일과 데스크톱을 자주 왔다갔다 하며 작업함. 모바일 앱과 웹 앱을 모두 이용하고 싶음.
- 팀과 협업: 팀원들과의 일정 조율, 업무 공유, 회의 일정 공유 등을 효과적으로 하기 위함.
- 실시간 업데이트: 중요한 일정이 변경될 때 즉각적으로 알고 싶음. 실시간으로 업데이트되는 기능이 필요함.

## 일정관리 프로그램에서 원하는 기능
- 다중 일정 뷰: 일간, 주간, 월간 일정을 한 눈에 확인할 수 있는 기능이 필요함.
- 업무 우선순위 설정: 중요한 일정이나 업무를 우선순위에 따라 표시할 수 있는 기능이 필요함.
- 팀과의 공유: 팀원들과 일정을 공유하고 업무를 할당할 수 있는 기능이 필요함.
- 알림 기능: 중요한 일정이나 업무의 마감일에 대한 알림을 설정할 수 있는 기능이 필요함.
- 프로젝트 관리: 각 프로젝트의 일정, 진행 상황을 한 눈에 볼 수 있는 프로젝트 관리 기능이 필요함.

이러한 일정관리 프로그램 페르소나의 특징과 일정관리 프로그램에서 원하는 기능을 고려하여 개발한다면, 스타트업 창업자 지훈이 보다 효율적으로 일정을 관리하고 업무를 진행할 수 있을 것으로 기대됩니다.

**Comment by Afresh2** [comment]
## 일정관리 프로그램
- 이름 : PopPlan

## 회사명
- 이름 : HW(한화)?

**Comment by Afresh2** [comment]
## 부글 -> 개굴 -> 거품 속에 갇힌 개구리 눈....🐸
![FroggyFriendsGIF](https://github.com/T2-Papillon/Main/assets/149090519/0955bf32-5663-4045-82dc-000df9676715)

![image](https://github.com/T2-Papillon/Main/assets/149090519/86e296c4-599a-4d87-b614-e4b419ad6a03)

**Comment by raheego** [comment]
맘에 들엇.. ㅎ
