### ISSUE TITLE
[공유] Spring 재교육 안내~☃️

### ISSUE THREAD

**Issue by raheego** [T2-Papillon/Main#21]
- [x] https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/issues/57

궁금한 spring 교육 있나여~
코멘트 여기에 남기거나 해당 이슈에 남겨보세여

**Comment by raheego** [comment]
난 MSA! 
msa 개념과 어떤식으로 사용되는지 궁금

**Comment by dana096** [comment]
security 에 대해 좀더 배우고 싶습니다!

**Comment by Afresh2** [comment]
spring boot MVC 실습
