### ISSUE TITLE
[질문사항 관련] Issues 타이틀 작성법 건의

### ISSUE THREAD

**Issue by dana096** [T2-Papillon/Main#25]
## [질문사항 관련] Issues 에서 라벨링을 세분화하였습니다. 

>Q[생성번호] _ [이슈 타이틀]  [관련 라벨]

ex) Q001_프로젝트 기획서 버전 관리 질문 ![image](https://github.com/T2-Papillon/Main/assets/145534055/023988a1-d9e9-4a73-a1f5-ddf578f7dbc7)

### 질문 주제
- 기획
- 백엔드
- 프론드엔드
- CI/CD
- 테스트

### 라벨링
![image](https://github.com/T2-Papillon/Main/assets/145534055/0c0e550e-2b34-46e4-bf92-41614e0e55de)

확인 후, 의견 부탁드립니다!
<br>
_ref) 라벨 색상과 아이콘 관련이나 이슈 관련해서 더 좋은 의견 있으시다면 말씀해주세요!_

**Comment by raheego** [comment]
생성번호 붙이는건 번거로워요! 꼭 기입해야하는지 궁금해요

**Comment by Afresh2** [comment]
저는 기존것도 좋고 생성번호 빼는것도 좋습니다~

**Comment by dana096** [comment]
ex) Q_프로젝트 기획서 버전 관리 질문  ![image](https://github.com/T2-Papillon/Main/assets/145534055/023988a1-d9e9-4a73-a1f5-ddf578f7dbc7)

그럼 위 예시 처럼 진행하도록 하겠습니다!😁

**Comment by raheego** [comment]
![LGTM](https://i.lgtm.fun/2pzb.png)
