### ISSUE TITLE
240315 요구사항 명세서

### ISSUE THREAD

**Issue by dana096** [T2-Papillon/Main#31]
### Todo 
- 요구사항ID 추가
- 중분류별로 나눠서 전제조건/제약사항 작성
- 참신한 소재로 마일리지, 추첨이나 쿠폰 같은 게임적 요소 추가
- 테스터가 완료가 된 화면을 찾아갈 수 있는 기능 추가 
(테스터를 위해 팝업이든 화면이든 검증해야하는 페이지로 바로 들어갈 수 있는 기능)

https://docs.google.com/spreadsheets/d/1uRO9aV2MluN2SZilx6fAVTUjLM9L1xdenN4830Lc0GU/edit#gid=27063674
<br>

### 변경사항
- 멘토님 피드백 반영하여 수정

**Comment by raheego** [comment]
![image](https://github.com/T2-Papillon/Main/assets/54056684/4bb8ef1b-3241-4370-af53-91a9547a67b3)
