### ISSUE TITLE
2차 멘토링 회의록 정리

### ISSUE THREAD

**Issue by Afresh2** [T2-Papillon/Main#32]
- https://docs.google.com/document/d/14woMuZGFCrDPNHByirwWW20DlcXTMz_4qDD9EWRra-Q/edit

**Comment by Afresh2** [comment]
# 멘토링 회의록 - [240315]
## 참여자
- 멘토: 남호원
- 팀 구성원: T2-Papillon 팀 멤버들


## 안건
**1. 변경요청서** 
- 추후 프로젝트 진행하면서 변경요청서 작성 예정
- 변경요청서 구성 항목 : 프로젝트명, 변경요청자, 변경요청ID, 요청일자, 변경요청명, 변경요청사항, 변경사유, 변경조치활동(조치자, 조치일), 승인여부(승인, 반려) 등
- 백로그
- 요구사항 명세서에 백로그의 내용을 담으면 좋겠다고 조언
- 백로그 = 요구사항 명세서 내용에 대해 협의를 마친 형태로, 백로그 내용을 토대로 WBS를 생성한다.
- 백로그 구성 항목 : No, Level1, Level2, Level3, Level4(백로그명), 백로그ID, 백로그 내역, 전제조건/제약사항, 백로그 유형, 중요도, 난이도, 신규개선, 수용여부, 출처, 현행업무재개도 업무기능ID(요구사항ID), 설계자, 고객담당자, 변경유형, 변경이력, 온라인배치구분, 비고 등

**2. WBS** 
- 최소한 WBS는 완성한 다음에 개발을 진행하기로 함
- 다른 문서들은 개발과 병행
- WBS 상세목록, 일정 명확하게 적기
- 화면설계, 컴포넌트 설계, 화면배치를 좀저 상세하게 작성하기
- WBS 구성 항목 : 번호(1.1.1 등), 작업이름, 가중치(%), 계획(시작일/종료일), Milestone, 진척률(계획, 실적, 차이, 상태), 활동구분, 계획산출물명 등

**3. 요구사항 명세서 피드백**
- 공통사항 부분도 대분류, 중분류, 소분류 적고, 요구사항 내용도 적어야
- 전제조건은 상세하게 쓰는게 좋고, 전제조건/제약사항은 빈칸이 있을 수 있다.
- 시각화 : 그래프 모양을 어떻게 만들지, 테이블에서 어떤 걸 우선순위로 보여줄지 등을 제약사항에 추가

**4. 테스트**
- 테스트 시나리오
- 테스트 수행(단위테스트) : 화면 하나하나 수행
- 통합테스트 수행

**5. 화면설계**
- 구성항목 : 시스템, 상세공정ID, 화면ID, 서브시스템, 화면명, CRUD, 설명 등

**6. 멘토님의 참신성 제안**
1) 오락 요소 가미 : 업무성과에 대한 보상을 룰렛 추첨 등의 게임 형태로 한다
2) 기능적 요소 : 하위업무에 대한 내용이 링크가 연결되어, 링크를 클릭하면 바로 그 업무 결과자료로 넘어갈 수 있게 한다.
- 위 2가지 내용은 실제 개발하지 못하더라도 우선 요구사항 명세서에 추가하기


## 다음 회의
- 차주 화요일(3/19), 금요일(3/22)

## 차주까지
- 요구사항 명세서, WBS, 개발환경 구성 완료

**Comment by raheego** [comment]
![image](https://github.com/T2-Papillon/Main/assets/54056684/27de04df-a745-4511-9909-d710795ab236)

**Comment by raheego** [comment]
![LGTM](https://i.lgtm.fun/2pvm.gif)
최고
