### ISSUE TITLE
1차 dev deploy - AWS CodeDeploy

### ISSUE THREAD

**Issue by choi3179** [T2-Papillon/Main#36]
- https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/issues/103
- [ ] 1. 초기 프로젝트 구조 설정 [PR URL]
- [ ] 2. local run test [PR COMMENT URL]
- [ ] 3. deploy aws ec2 url  [엔코아에서 만 접속 가능한 url, port 제출]

**Comment by raheego** [comment]
### vue 설치 완료
![image](https://github.com/T2-Papillon/Main/assets/54056684/1f2bf289-2671-40be-a9c1-4441c767191e)
https://github.com/T2-Papillon/front-vue/pull/1
