### ISSUE TITLE
[요청][GM] Github - Pull request 

### ISSUE THREAD

**Issue by raheego** [T2-Papillon/Main#38]
## Github - Pull request template 작성과 설정
pr 템플릿 양식이라는게 있네여 
gm 검토해주세요. 

- https://green-bin.tistory.com/16

그 외 참고 
- https://velog.io/@fj2008/github-소규모-협업-Git-hub설정PR요청

**Comment by raheego** [comment]
추가로 브랜치 보호 규칙도 검토해주세요 !

**Comment by dana096** [comment]
네 검토하겠습니다
검토 후 함께 회의하여 결정하면 될 것 같습니다!
