### ISSUE TITLE
시스템 아키텍처

### ISSUE THREAD

**Issue by choi3179** [T2-Papillon/Main#4]
- 프로젝트 기본 시스템 아키텍처 구성하기

**Comment by raheego** [comment]
![image](https://github.com/T2-Papillon/Main/assets/54056684/c125f8f1-0c36-4edf-aefc-d0c39a19bb23)

**Comment by choi3179** [comment]
![image](https://github.com/T2-Papillon/Main/assets/66417882/4de34419-0eae-403a-886c-160fea7d18f8)
![image](https://github.com/T2-Papillon/Main/assets/66417882/3d27d516-7ee2-42c0-824a-b6f9d3c92512)
### 핵심
- 로컬 개발환경을 그대로 dev, stg, prod에 배포한다.
- FE-nginx-BE-DB 개발환경을 docker compose로 구성한다.
- docker-compose 컨테이너 묶음을 하나의 EC2 인스턴스로 vpc에 생성한다.

**Comment by Afresh2** [comment]
![LGTM](https://i.lgtm.fun/2q4o.png)

**Comment by pySatellite** [comment]
개발 편의성 vs 운영 효율 두마리 토끼에 대한 고민을 담아 내시면 좋은 아키텍처가 될겁니다.

**Comment by choi3179** [comment]
- 시스템 아키텍처 1차 수정
![architecture drawio (1)](https://github.com/T2-Papillon/Main/assets/66417882/6dafc066-33d2-4493-91f0-62d1d0af593a)

**Comment by choi3179** [comment]
## 멘토님 전달 목적 아키텍처 1차 초안
![image](https://github.com/T2-Papillon/Main/assets/66417882/e4cec411-bbde-450f-920e-c8f4a57792e1)
- Frontend, Backend, DB를 각각 AWS EC2 인스턴스로 배포한다.
- Frontend, Backend, DB 모두 Docker를 이용해 개발 환경을 획일화하고 개발 환경 그대로 배포할 수 있도록 한다.
- 사용자는 Frontend가 배포된 EC2 인스턴스에서 제공하는 도메인으로 웹페이지에 접근한다.
- Frontend에서 웹 서버가 배포된 EC2 인스턴스 도메인으로 API 호출한다.
(DB와 Backend 웹 서버는 추후 하나의 EC2에서 배포하는 것으로 수정될 수 있다)
## 관련 문서
- https://docs.docker.com/get-started/overview/
- https://docs.aws.amazon.com/ko_kr/AWSEC2/latest/UserGuide/connect-to-linux-instance.html
