### ISSUE TITLE
ERD 수정합시다.

### ISSUE THREAD

**Issue by raheego** [T2-Papillon/Main#40]
- https://www.erdcloud.com/team/cEzh5JvujxvXqnqrC

**Comment by Afresh2** [comment]
![ERD](https://github.com/T2-Papillon/Main/assets/149090519/bdb13770-75bc-4f82-be6d-9aa7436b73f7)

**Comment by dana096** [comment]
![image](https://github.com/T2-Papillon/Main/assets/145534055/5aa63bed-b963-4070-a1c7-57646c78e33e)
