### ISSUE TITLE
[GM] Git commit , pr 컨벤션 정하기 

### ISSUE THREAD

**Issue by raheego** [T2-Papillon/Main#42]
pr title 컨벤션 수정요청 드립니다. 
컨벤션에 맞춰 수정하면 어떨까요.
이전에 issue 사항과 맞춰 코멘트 남기는 것도 참고부탁드립니다. 

### 수정요청사항
- https://github.com/T2-Papillon/Spring/pulls?q=is%3Apr+is%3Aclosed
![image](https://github.com/T2-Papillon/Main/assets/54056684/65bfdaf5-d26f-45da-bf52-f0591d1b5a89)

###
![image](https://github.com/T2-Papillon/Main/assets/54056684/230656d9-3e51-4236-91d0-7c3d1773802c)
![image](https://github.com/T2-Papillon/Main/assets/54056684/bf95a158-fcb8-4094-b294-eca2806e2ae9)

이전에 git 관련 문서를 만든 적이 있는데 컨벤션에 관한 내용도 포함되어 있어 공유해드립니다. 
아래 문서 참고 부탁드립니다. 
[git.pdf](https://github.com/T2-Papillon/Main/files/14715155/git.pdf)

**Comment by dana096** [comment]
위 내용 참고하여 GIT 브랜치 전략 작성하였습니다.
확인 후, 궁금하신 점이나 수정사항 있으면 말씀해주세요!

- https://github.com/T2-Papillon/Main/wiki/%5BPapillon%5D-GIT-%EB%B8%8C%EB%9E%9C%EC%B9%98-%EC%A0%84%EB%9E%B5
