### ISSUE TITLE
[공유] 산출물 평가 사전 알림 

### ISSUE THREAD

**Issue by raheego** [T2-Papillon/Main#43]
### 라댄에 올라온 내용 한 번 확인해주세요 
- https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/issues/119
 
![image](https://github.com/T2-Papillon/Main/assets/54056684/3717da50-bf92-4fc8-b8f9-587faf6838fd)

**Comment by dana096** [comment]
네! 확인 완료하였습니다
