### ISSUE TITLE
Releases & Tag v1.0.0 배포

### ISSUE THREAD

**Issue by dana096** [T2-Papillon/Main#48]
## Releases & Tag v1.0.0 배포

- [x] v1.0.0 - spring 배포 완료
https://github.com/T2-Papillon/Spring/releases/tag/v1.0.0

- [x] v1.0.0 - vue 배포 완료
https://github.com/T2-Papillon/front-vue/releases/tag/v1.0.0

**Comment by raheego** [comment]
![LGTM](https://i.lgtm.fun/2qyn.gif)
