### ISSUE TITLE
240306 멘토님 사전질문 리스트

### ISSUE THREAD

**Issue by raheego** [T2-Papillon/Main#9]
1차 멘토링을 위한 [사전질문 리스트] 를 작성해봐요 ^0^

**Comment by choi3179** [comment]
- 한화시스템에서 메인으로 잡고 계시는 분야가 어떤 건가요?
- 현업에서 일정 관리 때 필요한 기능인데 저희가 생각하지 못 한 부분이 있을까요?
- 면접 들어가시나요?

**Comment by Afresh2** [comment]
- 멘토님께서 멘토링에서 어떤 부분을 위주로 멘토링을 해주실 예정인지 궁금합니다.
- 저희가 진행하는 이와 같은 프로젝트에서, 어떤 태도 또는 어떤 프로세스 부분을 중요하게 생각하시는지 궁금합니다.

**Comment by raheego** [comment]
- 야근 많이 하시나요?
- 일정관리에 대한 차별성이 있다면 우리가 생각한건 ㅇㅇㅇ한데 어떠하신지

**Comment by dana096** [comment]
- 멘토링을 오프라인만으로 진행하는지?

**Comment by raheego** [comment]
![image](https://github.com/T2-Papillon/Main/assets/54056684/d5c9fc19-8118-4925-a416-4429a5a62f47)

위 내용 취합하여 멘토님께 전달드렸습니다.
**close**

**Comment by raheego** [comment]
```
[개인]
- 한화시스템에서 메인으로 잡고 계시는 분야가 어떤 건가요.
- 면접 들어가시나요.
- 포트폴리오를 보실 때 주로 확인하는 부분이 있으신가요.
- 멘토링에서 어떤 부분을 위주로 멘토링을 해주실 예정인지 궁금합니다.
- 오프라인만으로 진행하는지 궁금합니다.

[프로젝트]
- 현업에서 일정 관리 때 필요한 기능인데 저희가 생각하지 못 한 부분이 있을까요.
- 보안을 위해 Spring Jwt를 사용한다고 배웠는데 실제 현업에서도 사용하시나요. 이번 프로젝트에 같이 추가하는게 좋을까요.
- 일정관리에 대한 차별성이 있어야 한다면 어떤게 있을까요. 우리가 생각한 차별성에 대한 피드백 사항
- 저희가 진행하는 이와 같은 프로젝트에서, 어떤 태도 또는 어떤 프로세스 부분을 중요하게 생각하시는지 궁금합니다.
```
